FROM node:latest

WORKDIR /usr/src/app

COPY . ./

RUN npm install

CMD "node Game.js"
# CMD "npm run start"

# COPY package*.json ./

# RUN npm install

# COPY . .

# EXPOSE 8080

# CMD [ "node", "server.js" ]